### ISSUE TITLE
Cron Job Not Working

### ISSUE THREAD

**Issue by hamd01** [LiveHelperChat/livehelperchat#1017]
I have been trying to get cron jobs working, but for some reason the cron just wont run due to errors.

This is the command I run;

/usr/bin/php5 /home/sites/screensquad.co.uk/public_html/home/sites/screensquad.co.uk/public_html/team/cron.php -s site_admin -c cron/workflow

this is the result;

![output](https://cloud.githubusercontent.com/assets/28013354/25394870/27523d6e-29d7-11e7-8f0d-2281351ef09d.png)

Not being able to run the cron job is a big problem, as I have several tasks which require it.

I have also tried running the cron from a browser window, and it gives the following error

`Fatal error: Uncaught Exception: Setting with section {site_access_options} value {} in /home/sites/screensquad.co.uk/public_html/home/sites/screensquad.co.uk/public_html/team/lib/core/lhconfig/lhconfig.php:23 Stack trace: #0 /home/sites/screensquad.co.uk/public_html/home/sites/screensquad.co.uk/public_html/team/cron.php(83): erConfigClassLhConfig->getSetting('site_access_opt...', false) #1 {main} thrown in /home/sites/screensquad.co.uk/public_html/home/sites/screensquad.co.uk/public_html/team/lib/core/lhconfig/lhconfig.php on line 23`

I have spoken to support directly and have ensured the following;

1. All paths are correct
2. Recopied the entire folder structure from a fresh download, to ensure no missing files
3.  Tried various version of PHP....currently 5.6

Does anyone know what might be causing this problem and how I might rectify it?

**Comment by PeopleInside** [comment]
Thank you for submitting your issue here.
Thanks also for had try to reupload all necessary file and take time to test different php version. PHP 5.6 is actually fine, supported by live helper chat.

Regarding your issue I can only suggest to try a clean install and to see if the cron issue is the same, in that case can be a bug or issue in live helper chat however this topic will be viewed and maybe replied from the chat owner.

In the case all work in live helper chat and you cannot move to a new installation you can consider to ask commercial support to the chat owner. Details is on site and on the forum also (on how asking commercial support)

For now just wait and follow this topic. Chat owner is busy so reply can take some time.
Thank you!

**Comment by hamd01** [comment]
Thank you for your reply.

As I test I have just downloaded a fresh copy of livehelperchat-master.zip and unzipped, and copied all files to the server again.  But sadly it has not resolved the error.

**Comment by remdex** [comment]
Hi,
Cronjob has to be run from root folder. Something like this
cd /home/sites/screensquad.co.uk/public_html/home/sites/screensquad.co.uk/public_html/team/ && /usr/bin/php5 cron.php -s site_admin -c cron/workflow
