### ISSUE TITLE
Widget Reloads Page Inside Widget v2.60

### ISSUE THREAD

**Issue by eCommerceGorilla** [LiveHelperChat/livehelperchat#1024]
I have tried a number of different versions. Each is reloading the embedded page into the widget.

Is there a solution to this issue? Installed a number of the most recent versions and they all seem to have the same bug.

**Comment by PeopleInside** [comment]
GitHub is usually here used for report BUGS or issue than cannot be solved in the official forum.
Please if you need discuss about your issue, use the Forum.

There is no BUGS regarding your issue seems you have not compatible server configuration but without look at the URL where your widget is and is having this issue ... is really difficult help you.

**Comment by eCommerceGorilla** [comment]
@PeopleInside I apologize for the lack of information, I've been working with the hosting provider to locate the issue. It is running into a strict mod security issue that it is rating as an xss attack that the earlier versions of the program didn't trip for some reason. I'm closing this topic as this isn't something directly related to Live Helper Chat.

**Comment by PeopleInside** [comment]
Yes sure, the issue is on something into server configuration :-) you are welcome! I AM happy to read about you was able to find what is wrong :)
