### ISSUE TITLE
remove/hide bots from visitors listing

### ISSUE THREAD

**Issue by centoasa** [LiveHelperChat/livehelperchat#122]
Please, remove/hide bots (google and other bots) from visitors listing.

**Comment by salsero72** [comment]
Hello,
I'd need this also.
I found many instances of bingbot, (coming from USA , referer contains +http://www.bing.com/bingbot.htm) with many IPs.
Of ourse I can block IPS, but would be useful a feature to block users not only by IP.
"bingbot" for instance could block all the instances of this spider (which runs from many different IP) so yandex or many others.
Sometimes an online user bothers with many silling questions day after day, just because they have the time to do it. And often they do not have static IP. Then filter by cookie would be nice also. Even though I know cookies can be destroied
