### ISSUE TITLE
Help - Survey with widget

### ISSUE THREAD

**Issue by phamorais** [LiveHelperChat/livehelperchat#1254]
In my company, we use the widget embedded in GLPI. When the operator finishes the service and sends the satisfaction survey, the user responds without problem, but when the user clicks save the widget returns the search to the user, causing the chat to be reopened. Does anyone know how to solve

Version : 2.91 and 2.86

Gif with a exemple 

![gif](https://user-images.githubusercontent.com/35368369/44343512-7fa4ed00-a464-11e8-8217-4c1fd9f0acdc.gif)

**Comment by remdex** [comment]
Hi,
Sorry but it's custom integration and i can't reproduce it locally... I can offer only commercial help in that case...

**Comment by ledsonsilva** [comment]
When a search is sent to the user, the user then responds, then the user ends the chat and the question form reappears, previously filled in with the previous answers. The form should not appear again because it has already been answered, and it does not have any settings made for the form to appear at the end of a chat.

**Comment by phamorais** [comment]
How are you? Everything ok?

Well, this is not a customization but rather the use of the embed code provided by the tool itself.

I Thing this is a bug.

**Comment by remdex** [comment]
Sorry, but on my dev environment all works. If customer does not close widget and just hit refresh he comes back to chat. But he cannot refill survey just. He has to close widget explicitly.
