### ISSUE TITLE
Unable to login using Chrome

### ISSUE THREAD

**Issue by simsketch** [LiveHelperChat/livehelperchat#1272]
For some reason I can't always login using Chrome, but it works fine in Edge and Firefox.

It seems to only work if i use the browser-saved credentials.

**Comment by remdex** [comment]
Hi,

**Comment by mjhd** [comment]
Wow - I'm having this problem as well, thanks for the"help" guys 🙄

**Comment by PeopleInside** [comment]
@mjhd are you able to login https://demo.livehelperchat.com/site_admin/user/login with Chrome?
Username admin passw: demo

If yes so the problem is not live helper chat but can be your side.
Are you using the latest version 3.25?

Hoping you have already resolved the issue. Not clear to me if you solved or still facing issue.

**Comment by mjhd** [comment]
Yes, and like OP - I can log in in ALL other browsers, only Chrome is having this problem:

**Comment by mjhd** [comment]
![live_chat_issue_initial](https://user-images.githubusercontent.com/5019808/70476081-d59f0900-1a8a-11ea-8b90-ef81ac9ff4f6.png)

**Comment by mjhd** [comment]
![live_chat_issue_after](https://user-images.githubusercontent.com/5019808/70476094-dcc61700-1a8a-11ea-930b-bd62cb7cd770.png)

**Comment by dkwiebe** [comment]
@mjhd Chrome shows that you have an error in the console.  What is it?

**Comment by PeopleInside** [comment]
@mjhd 

1. Please do not create multiple message one after one, 3 messages can be just one. "Please do not spam".
2. The issue is not live helper chat if you can login into the demo. The issue is your side.

**Comment by mjhd** [comment]
Gee thanks... And, No, it isn't - if one browser can't login and all others can, the issue is with your application... Or are you suggesting it's with Chrome? - because the sever is working flawlessly. That error was a 404 related to a plugin btw - but I already disabled all plugins as well, and the problem persists on a stock Chromium install on Centos7 also, so it's not from that...

**Comment by mjhd** [comment]
Nvm - I'll just do it myself...

**Comment by mjhd** [comment]
Btw I tried serving with both NGINX and Apache - so you may want to hunt this bug down at some point - laters

**Comment by PeopleInside** [comment]
@mjhd  again please don't spam with multiple message. You can edit your last message if you need add information. If you continue to generate multiple message topic can be locked as first action. You can may try the incognito mode of Chrome with all extension disabled.

**Comment by mjhd** [comment]
Are you fucking serious dude? Thanks - but no thanks 🖕

**Comment by PeopleInside** [comment]
@mjhd  i reported your message to GitHub as abuse. My support for you ends here.
