### ISSUE TITLE
Forum : Upgrading MySQL 5.6 to 5.7 -- chat no longer working

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1275]
See forum topic here: https://forum.livehelperchat.com/viewtopic.php?id=3239

**Comment by rehv** [comment]
Hello! I'm the user referenced in the post. I have since then "corrected" the issue. 

The error was originally reported on #1026 and about 2 or 3 forum posts (took a bit of time to locate, but this kind of error should occur on any MySQL 5.7+ installations -- at least on Linux distributions, my server is using RHEL 7). 

It is related to MySQL and the referenced steps to correct the problem are also listed there (#1026). Since that issue was never responded to, I'm writing this in hope the issue gets attention, because the "list online operators" function is the only conflicting code in the dashboard (everything worked fine without any changes if I disabled "List Online Operators" -- as per other user suggestion).

Thanks in advance for your time, and thanks again to Marco for opening this issue.

**Comment by remdex** [comment]
https://forum.livehelperchat.com/viewtopic.php?id=2519

**Comment by PeopleInside** [comment]
Same issue here: https://forum.livehelperchat.com/viewtopic.php?id=3269
