### ISSUE TITLE
WordPress plugin download page redirects to spam

### ISSUE THREAD

**Issue by irishblake** [LiveHelperChat/livehelperchat#1365]
https://livehelperchat.com/wordpress-plugin-for-live-helper-chat-427a.html

this goes to scam.
Cant download plugin to use.
What next??

**Comment by PeopleInside** [comment]
Hi @irishblake , very sorry for this issue seems the website linked is no more avaiable and the redirect goes to a spam or scam website.

I informed @remdex the chat owner.
I don't suggest to use a plugin in Wordpress as this can be not updated. You can install live helper chat than put in the Wordpress footer or in headers the Embed code for have the live chat.

If you are not in a VPS or managed server i suggest to use an hosted version as you can have issue on a shared hosting also some of this deny in the terms the use of applications that can required dedicated resources.

Live helper chat can be downloaded here: https://livehelperchat.com/article/static/5
You can read the [Ultimate tutorial for pro active chat installation and chat install](https://livehelperchat.com/ultimate-tutorial-for-pro-active-chat-installation-and-chat-install-217a.html)

Please use a supported PHP version: https://www.php.net/supported-versions.php

Here is how generate and use Embed Code: https://livehelperchat.com/how-to-embed-live-helper-chat-generated-javascript-in-wordpress-207a.html

**Comment by irishblake** [comment]
Thank you, Marco.

Very helpful, and i'll do all as you suggest RE footer add on.
Thanks again~

 with Best Regards
Blake O'Ruairi

678-929-7721 direct

**Comment by PeopleInside** [comment]
@remdex should remove this bad URL soon; i will keep this issue opened until will be not resolved.
Thanks for the report.

**Comment by PeopleInside** [comment]
Thanks for the report, issue has been resolved.
