### ISSUE TITLE
How to integrate osticket with livehelperchat???

### ISSUE THREAD

**Issue by sunil10119** [LiveHelperChat/livehelperchat#1387]
Hello,
I have create an osticket extension in livehelperchat. When I click on "create a ticket" button it show an alert box with "Unable to create ticket: <html></html>" can you help me out...
Thanks
![osticket](https://user-images.githubusercontent.com/56536984/66738758-d4879c00-ee8c-11e9-8982-2994528afb1e.png)

**Comment by PeopleInside** [comment]
Hi @sunil10119 what is your PHP version?
Let me check, maybe this extesion has not been updated.

I use live helper chat and Osticket but without need to use the plugin.
If you need create ticket by the open chat than you need the plugin but if this not work you must wait a fix and i don't know if that can come.

I use OsTicket just for offline message. Offline message are sent to the ticket email address from my domain name address. Live helper chat puts the visitor email address in the reply to so with a Osticket filter i can open ticket for offline message with the visitor email address.

You can see how to create the filter in OsTicket here: https://s3.gifyu.com/images/demostration-osticket.gif

Maybe if you need open a ticket from chat this can be done manually until a reply or a fix can't come here.

The OsTicket extension is not updated since Febrary 2019, live helper chat has been upgraded different times in all this month.

I don't use the extension and if there are issues on the code i cannot help about that.
Any server error log? Any error inside Osticket logs?
