### ISSUE TITLE
Chat box loading

### ISSUE THREAD

**Issue by shahmirf** [LiveHelperChat/livehelperchat#1441]
In version 3.29 if feature avoid loading is not activated, Chat box loading is not working, when the user click to open chat box, it will disappear for a while until the chat start form load completely.

**Comment by remdex** [comment]
I'm not sure what you mean? Can you give steps by step to reproduce?

**Comment by PeopleInside** [comment]
@remdex I think @shahmirf means he expect to see the previous circle animation of loading when widget is clicked and the option to preload the widget is not enable.

I found the same behaviour but i don't think is really an issue, now seems @shahmirf has decided to report the same.

If this issue is invalid you can close it.
Maybe in the new widget if the pre loading is disabled you have just simply a delay before you can see the widget. No loading icon showed.

This if I'm not wrong happens also with the stable widget (not the beta).
For the steps @shahmirf can provide it.

**Comment by remdex** [comment]
In general I close this issue as invalid.
1. Widget preload works only for old widget chat widget. It's not implemented in chatbox at all.
2. New widget does not need this preload at all.
