### ISSUE TITLE
Chat's iframe renders current page html on "minimize" button is clicked.

### ISSUE THREAD

**Issue by AdamHider** [LiveHelperChat/livehelperchat#1465]
My problem is that chat's iframe renders the entire active page html code on "minimize" button is clicked. When I go to any other page, such thing happens again. 
This problem dissapears only if the page is refreshed. But than, on "minimize" is clicked - issue with render appears again.
Btw, popup works fine. Problem is related with widget view only.
Will be very glad to hear some reasons and possibilities of resolving such thing. Thank you very much.

**Comment by remdex** [comment]
I really did not understood how to reproduce the issue..Can you reproduce on demo.liveheperchat.com?

**Comment by AdamHider** [comment]
Unfortunately, it's impossible, because the problem is on client side. 
Admin side works great. I could attach a link to my website. Hope it will be helpful
https://cereyan.market/index.php?route=common/home
Thank you

**Comment by remdex** [comment]
I'm sorry but I still can't reprocuce the issue :D

**Comment by AdamHider** [comment]
I haven't mentioned, that problem occurs only on PC. Mobile version works great.

**Comment by PeopleInside** [comment]
Hi, the issue seems happen only on Firefox not in Chrome: 

1. open the chat widget on your webpage
2. minimize the widget

Sometimes the widget is also not loaded.
Can you try to put your widget in a different page? Maybe the issue is related to your website or server configuration.

I don't think is LHC issue.

**Comment by AdamHider** [comment]
"Can you try to put your widget in a different page?" 
I tried, but the problem appears on all pages. 
Just tested on different browsers. It's true that PeopleInside said: render issue occurs only in firefox. Chrome and Edge work well.
Thanx guys!

**Comment by PeopleInside** [comment]
@AdamHider create a new HTML page balnk and put the widget inside.
The issue persist? If not the issue is in your website theme. I don't know if remdex can help with that.

The same issue happen also if you replace your widget with the demo one (embed code of the demo widget)?

Maybe the developer console fo the browser can help you to underastand where the problem is. I'm not a developer so my knowledge is very limited but i like to found issue and try to resolve... not alwyas i have power to do so.

I'm just giving you some suggestion.
The issue I can see is showed in the following screenshot made by Fireox:

![img](https://user-images.githubusercontent.com/5006150/81564892-bb9a8700-9398-11ea-9699-aca8c4b7c70a.gif)

**Comment by PeopleInside** [comment]
I see there are some console errors.
![Immagine](https://user-images.githubusercontent.com/5006150/81565037-ff8d8c00-9398-11ea-92ff-eafa001ddda3.png) but unable to say why yu have thoose issues.

What version of PHP are you using?
What version of live helper chat are you using?
Have you edited the LHC code?

**Comment by AdamHider** [comment]
"I see there are some console errors."
Yeah, haven't checked that page completely. 

Well, the problem is in opencart, so creation on empty html and chat module in it works fine. I will dig deeper, and hope that will find the root of that problem and will share with you. It would be helpful, because both opencart 2 and 3 with absolutely independent themes installed have that problem.

Thank you, guys! You rock!

**Comment by remdex** [comment]
It looks like somehow your site interferes with lhc script although lhc itself is written independent way but you somehow manager to override what it does internally  and only in firefox :)

**Comment by remdex** [comment]
looks like also on any action your site overrides any lhc iframe content :)

**Comment by AdamHider** [comment]
If I will resolve that problem, I will share it with you in order you to mention that info in the documentation of the project.
Thank you, mate!=)

**Comment by remdex** [comment]
Just is it default open cart setup which does not work? If so i could try to find poblem myself tomorrow :)

**Comment by AdamHider** [comment]
Whether it was default or not I don't know for sure for now. Actually, it seemed to be so. But the fact is that both v2 and v3 use some theme overrides, but that themes are completely different. After that I've made such conclusion, but, after all, still not sure. Generally because coding taught me, that I never can be 100% sure=))

**Comment by remdex** [comment]
So I have installed fresh OpenCart and was able to reproduce the issue. I'll see now what's happening and let you know :)

**Comment by remdex** [comment]
Fixed please update to version from github and all should be fine now :)

**Comment by AdamHider** [comment]
Oh, thank you man!! Everything works great! You are the best!=))
