### ISSUE TITLE
User Sign In Before Chat

### ISSUE THREAD

**Issue by noellarkin** [LiveHelperChat/livehelperchat#1775]
I'm wondering if Live chat helper has a user management system, where the visitor has to log in (not provide email, but log into an existing account) prior to chatting - - similar to how many wordpress live chat plugins work. I'm sorry if this isn't clear, I'm still trying to find my way around the live chat.

**Comment by remdex** [comment]
You can look at paid chat function. So users would be able to start chat only if valid hash is there.
https://doc.livehelperchat.com/docs/paid-chats/

Otherwise there is no out of the box mechanism for user validation before chat. 

Also same can be achieved using

 * https://doc.livehelperchat.com/docs/bot/rest-api-to-fetch-customer-info
 * https://doc.livehelperchat.com/docs/bot/check-conditions you pass JS variable and afterward in the bot check for it's presence. If it's found you transfer to pending state chat if not write , please login first to be transferred to operators.

In general many options with some configurations :)
