### ISSUE TITLE
Widget will not load on pages that have change their document domain.

### ISSUE THREAD

**Issue by tslater2006** [LiveHelperChat/livehelperchat#1839]
We are trying to load the live helper chat widget v2 on a PeopleSoft page. PeopleSoft pages tend to update their document domain such that when visiting `foo.site.com` the document.domain is set to `site.com` which is allowed (see: https://developer.mozilla.org/en-US/docs/Web/API/Document/domain#setting_the_domain).

The problem seems to be around the wrapper's `index.js` and the react app's `chatWidgetListener.js` because they take the origin of the message (which would be the full `foo.site.com`) and enforce that it matches the document.domain.

We have temporarily patched these files from

```
if (originDomain !== document.domain && ...
	return;
}
```

to 

```
if ((originDomain.endsWith(document.domain) === false) && ...
	return;
}
```

This seems to allow the widget to load correctly on our PeopleSoft pages, but we would like to see this officially supported if possible.

**Comment by remdex** [comment]
Well, as your article states it's depreciated. So you will have to keep your fork, or just stop changing it...

**Comment by remdex** [comment]
In official version it won't be added, because I have various clients hosting on various environments. 

Alternatively you can try to set in main settings file. Playing around with this value and 

```
'trusted_host_patterns' =>
      array (
        0 => '^devmysql\\.livehelperchat\\.com$',
        1 => '^.+\\.livehelperchat\\.com$',
),
```

You might get it working.

```
'site', 'site_address'
```

This is the part that returns hosts which afterward is used also in that domain check. So I suppose if this part would return same host always and as you set it to your domain it might work perhaps without any modifications.

https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhcore/lhsys.php#L495
