### ISSUE TITLE
Detect user local time and show  in online visitors list

### ISSUE THREAD

**Issue by remdex** [LiveHelperChat/livehelperchat#424]
Like we can detect user country we should also show user local time.

**Comment by bkonia** [comment]
I actually find the time zone display in the online visitors list annoying and distracting. It displays the time zone in a long format like "America/Los Angeles", which is confusing, because it looks like a location. Could you please provide an option to display the time zone in a short format, like UTC-8 and/or hide the display of the time zone entirely?
