### ISSUE TITLE
Set "From" in Chat Offline Form E-Mail

### ISSUE THREAD

**Issue by Ennosuke** [LiveHelperChat/livehelperchat#616]
We are using a ticket system for incoming emails so also for the emails coming from the chat when no operators are online. The problem is that the lhc does not set the From field properly either it's a value we have set in the background or it's empty, both aren't really good solutions because it messes with the search feature of the ticketing system. It would be great if the customer mail is set as from or if there was atleast the option to do so.

**Comment by remdex** [comment]
Ok,

So the problem is. If i would do that with gmail etc mail would go directly to spambox, because that means i'm faking sender and sender in this case hosting page not user and i Just cannot do that.
At the moment LHC sets use mail as Reply-To mail.

Additionally you can take a look at https://github.com/LiveHelperChat/osTicket how integration with third party ticketing system is done. It's more proper way to do that.

So in general I cannot help you there... Like doing what you are asking is just faking server which is invalid solution.

**Comment by remdex** [comment]
Another thing if you would let know what ticketing system you are using perhaps i could write proper integration...

**Comment by Ennosuke** [comment]
I understand your concerns that's why I said maybe as an option. So default is the way it currently is, but there is the option to change it. I think it would be a neat thing to add. We currently have a smallish patch like 1 line of code that does what we want, but honestly it's annoying to apply it everytime we update LHC.

**Comment by remdex** [comment]
Ok I see. Perhaps just will add this option in mail settings part.

**Comment by Ennosuke** [comment]
Nice to know that you may consider it, would you mind reopenning the issue and setting the correct label? It's kinda bugging me :)

**Comment by remdex** [comment]
This stuff most likely will be added to mail templates them self so user will be able to control that at mail level.
