### ISSUE TITLE
Name bar not displayed after message from live support

### ISSUE THREAD

**Issue by metrotyranno** [LiveHelperChat/livehelperchat#680]
If an operator writes a message behind an automatic message his name is not displayed.

http://puu.sh/hToL2/0f817e0386.png

**Comment by PeopleInside** [comment]
This is not bug.

Inviato da dispositivo mobile. | Sended  by mobile device
Il 19/Mag/2015 22:45, "metrotyranno" <notifications@github.com> ha scritto:

**Comment by PeopleInside** [comment]
:o

**Comment by PeopleInside** [comment]
Yes issue confirmed

**Comment by PeopleInside** [comment]
Issue are not visible from the operator during the chat.

Issue is present on customer side and when chat is closed you can see the issue on the closed conversation.

**Comment by metrotyranno** [comment]
Issue is vissible from operator chat for me (official release)

http://puu.sh/hTqWW/82c96ceb55.png

**Comment by PeopleInside** [comment]
Thanks.
I have tested on demo and this is what I can see.

Operator side chat opened:
![1](https://cloud.githubusercontent.com/assets/5006150/7714276/adb559b8-fe7d-11e4-952f-4138a2c330b8.png)

Customer side
![2](https://cloud.githubusercontent.com/assets/5006150/7714283/b7132602-fe7d-11e4-94db-b17dadece39a.png)


On the operator side the issue is visible when chat is in status closed. In closed list chat if chat is opened issue are also present in the saved conversation.

**Comment by metrotyranno** [comment]
In this scenario i initiated a chat from the admin area as a chat invitation.
[image](http://puu.sh/hTrwC/61709f86a3.png)

**Comment by PeopleInside** [comment]
So waiting this BUG can be fixed ^_^

**Comment by remdex** [comment]
Yes, it's a bug, but tricky to fix. Anyway i'll see what can i do.
