### ISSUE TITLE
Bug in Anti-Spam Feature

### ISSUE THREAD

**Issue by indraveni** [LiveHelperChat/livehelperchat#730]
Hi,

I am a security tester and on my way , I found livehelperchat used by my client for their website. Its found that you have mentioned in the feature set of new version of this application that it supports anti-spam without a captcha. But this isn't working as described.

I have executed a pitchform submission on the livehelperchat form page and found that all submitted payloads are submitted to the server successfully, and the server is filled with spam messages in a minutes time.

Attached screenshot of admin panel, where span chat messages are logged.

![livehelperchat_spam](https://cloud.githubusercontent.com/assets/8177068/8924674/955b545e-351d-11e5-9b26-eb3d4e9a6194.PNG)

**Comment by remdex** [comment]
Well, two things.
1. Captcha can work with php sessions and without.
2. If captcha mode is working without without sessions. Spam bot let say would have to write full workflow to post a form. Make request to get captcha string and only then make a post. This token expires every 10 minutes.
3. If working with php sessions token is stored in PHP session and spam bot has to start php sessions.
4. By default php session captcha is disabled becuse of third party.

So I really don't think that something more will be done in your case. What human creates, human can break. As for notice there was 0 reports about spamming in LHC installs... Also if what users can block IP ranges etc.

**Comment by remdex** [comment]
If you find any more smarter way to do it. Go ahead and create a pull request :)

**Comment by indraveni** [comment]
Hi,

Was just exploring your reply to my email. As you said , you are using php
sessions and expires every 10 mins. But this, 10 mins can be controlled for
actual chat form, rather than for the first form, where user enters
username and his message.

Why should my server accept more than one username with the same php
session? Once a username is sent to server, he/she can continue the chat.
Any further requests received to server with same captcha with username can
be restricted. Isn't it?

regards
indraveni

**Comment by remdex** [comment]
Not sure i understood you but take a look at these checks. It should make more clear
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/modules/lhcaptcha/captchastring.php
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhchat/lhchatvalidator.php#L158-L167

In general because of third party cookies, PHP sessions are disabled for frontend visitors. I cannot store any information in php sessions. Because they just don't work.

In any case you are free to create a pull request if you see where something could be improved :)
