### ISSUE TITLE
Sugestion: make the first department selection blank

### ISSUE THREAD

**Issue by DPComp** [LiveHelperChat/livehelperchat#772]
As described in forum, https://forum.livehelperchat.com/viewtopic.php?pid=6163

"Is there a way to when the user enter in the chat (as example, https://demo.livehelperchat.com/), to not show the first department option as default, like show in blank, to make the user choose the correct department?
Like I have 3 departments: A, B and C.
When the user enters in the page to fill the form to start a chat, I which to show the first option blank, to make him choose between A, B and C, since now it shows A as default and almost 90% of the time, it goes there, even if he wants to go to another?
Version of our chat: 2.13
PHP: 5.3.2
MySQL: 5.1.61"

If possible, could you make a way that the user will be obligated to choose a department, instead of always sugesting the first one?

Thanks.

**Comment by Joeboyc2** [comment]
Hi,

This should be simple enough to do, you'll just need to add another <select> option in to the template, If your not sure how to do this ill give I'd a go on Monday and post a pull request to see If we can get it added. 

It might need some further logic however because everyone may boy want it to work like that, so maybe @remdex could take a look when he has a chance

**Comment by DPComp** [comment]
Hello.
It was him who suggested me to come here and post that.
Thanks.

**Comment by remdex** [comment]
Implemented as one of the theme option. 
https://livehelperchat.com/new-version-2.39v-bubbles-chat-and-some-more-changes-434a.html
